Found Phone型アドベンチャーゲーム コアシステム仕様書1. システム全体構成 (Architecture)デザインパターン: MVC (Model-View-Controller) に準拠。必須ライブラリ:Yarn Spinner: シナリオ・フラグ管理DOTween Pro: UIアニメーション制御Newtonsoft.Json: セーブデータのシリアライズTextMeshPro: テキスト描画・絵文字アイコン表示2. モジュール別詳細仕様A. シナリオ制御モジュール (ScenarioManager)Yarn Spinnerの実行エンジンをラップし、Unity側の演出へ変換する司令塔。役割: .yarn ファイルの読み込み、コマンドの解釈、UIへの命令出し。Yarnコマンド定義（カスタムコマンド）:AIに実装させる際、以下のコマンド処理を登録させます。<<Message "CharID" "Text">>指定IDのキャラからのメッセージとしてUIに表示。<<Image "CharID" "ImageName">>画像メッセージを送信。<<Wait "Seconds">>指定秒数待機（シナリオ進行を一時停止）。<<Typing "Seconds">>「入力中...」アニメーションを表示し、指定秒数後に解除。<<ChangeStatus "CharID" "Status">>キャラクターの状態（オンライン/オフライン/取り込み中）を変更。B. チャットUIモジュール (ChatUIController)画面描画とスクロール制御を担当。Prefab構成:ChatBubble_Left (相手用): 左寄せ、背景グレー、アイコンあり。ChatBubble_Right (自分用): 右寄せ、背景アクセントカラー、アイコンなし。TypingIndicator: 波打つ3点リーダーのアニメーション。動的レイアウト要件:VerticalLayoutGroup (Spacing: 20程度)ContentSizeFitter (Vertical: Preferred Size)重要: メッセージ追加時、自動的に最下部へスクロールさせるが、「現在ユーザーが過去ログを読んでいる（スクロール位置が上にある）」場合は強制スクロールさせないロジックを含めること。C. データ永続化モジュール (SaveManager)ゲームの状態を保存・復元する。保存すべきデータ構造 (JSON):JSON{
  "YarnVariables": { ... }, // Yarn Spinnerの全変数（フラグ、好感度）
  "ChatHistory": [
    { "CharID": "A", "Type": "Text", "Content": "Hello", "Timestamp": "10:00" },
    { "CharID": "Player", "Type": "Image", "Content": "photo01.png", "Timestamp": "10:05" }
  ],
  "CurrentNode": "Chapter1_Start", // 現在実行中のシナリオノード
  "SystemSettings": { "Volume": 0.8, "TextSpeed": 1.0 }
}
実装要件:Yarn.MemoryVariableStore を継承または拡張し、変数のダンプとロード機能を実装する。アプリ中断時（OnApplicationPause）および重要ポイントでオートセーブを行う。3. アニメーション・演出仕様 (Animation Specs)AIに「DOTweenを使って以下の挙動を実装せよ」と指示する項目です。① メッセージ受信・送信アニメーションただ表示するのではなく、有機的な動きをつける。出現: Scale 0 → 1 (Ease: OutBack) 0.3秒フキダシが「ポンッ」と膨らんで出る動き。スライド: 新しいメッセージが出た時、既存のログ全体が上にスライドする動き (Ease: OutCubic)。② タイピングインジケーター (Typing...)表示: 相手のフキダシとして出現。アニメーション: 3つのドットが Sin 波で上下、または透明度が変化するループアニメーション。消滅: 本メッセージが表示される直前に、フェードアウトして消える。③ 画像の表示チャット内のサムネイルをタップした際、背景を暗転させ、画像を画面中央に拡大表示するライトボックス風の演出。4. 素材アセット要件 (Assets Requirement)独自素材を最小限にするための定義。アセット名設定・プロパティ用途Bubble_Base.pngSprite Mode: SingleMesh Type: Full RectBorder (9-Slice): 上下左右 20px全メッセージの背景。色変えで自分/相手を区別。Avatar_Mask.png円形の画像コンポーネント: Maskアイコンを丸く切り抜くため。FontsNoto Sans JP (本文用)Material Icons (アイコン用)UIの全テキストとボタン類。